# Generated by Django 2.2.dev20181116092559 on 2018-11-16 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOnwership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Deck')),
            ],
        ),
    ]
