# Generated by Django 2.2.dev20181116113213 on 2019-01-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_cardonwership'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cost',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.TextField(default='normal'),
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(to='game.Card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='effect',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='CardOnwership',
        ),
    ]
