# Generated by Django 2.2.dev20181116113213 on 2019-01-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190120_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='element',
            field=models.TextField(default='normal'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.TextField(default='terrain'),
        ),
    ]
