# Generated by Django 2.2.dev20181116113213 on 2019-01-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190120_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='defense',
            field=models.IntegerField(default=0),
        ),
    ]
