# Generated by Django 2.2.dev20181116113213 on 2019-01-20 17:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190120_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one', models.TextField(max_length=100)),
                ('deck_one', models.TextField(max_length=100)),
                ('bot', models.BooleanField()),
                ('player_two', models.TextField(max_length=100)),
                ('deck_two', models.TextField(max_length=100)),
                ('state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
