# Generated by Django 2.2.dev20181116113213 on 2019-01-20 18:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bot',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_two',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_two',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
