# Generated by Django 2.2.dev20181116113213 on 2019-01-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190120_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(related_name='cards', to='game.Card'),
        ),
    ]
