# Generated by Django 2.2.dev20181116113213 on 2019-01-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190121_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.TextField(max_length=999999, null=True),
        ),
    ]
