    {{ container_name }}:
        container_name: {{ container_name }}
        build: ./django
        restart: always
        volumes:
            - ../:/app
        ports:
            - {{ port }}:8000
        command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]